// <auto-generated />
namespace Chow_Kenneth_hw4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedrequirements : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedrequirements));
        
        string IMigrationMetadata.Id
        {
            get { return "201610022035561_added requirements"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
